###########
# site.title

title:    'Jekyll Starter Theme V2'
subtitle: 'Another Static Site Quick Starter Theme'


nav:
- { title: 'Home',              href: '/' }
- { title: 'About',             href: '/about.html' }
- { title: 'Articles',           href: '/articles.html' }
- { title: 'Newsletters', href: '/newsletters.html' }
- { title: 'Newsletter',                href: 'http://tinyletter.com/theinclusiveleader' }
- { title: 'Medium',                href: 'https://medium.com/@elnatnal' }
- { title: 'RSS',                href: '/feed.xml' }

#########################
# more settings

markdown: kramdown

plugins:
  - jekyll-feed

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

